# Generated by Django 4.2.17 on 2024-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_packages', '0001_travel_pacckages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelpackage',
            options={'verbose_name': 'pacote de viagem', 'verbose_name_plural': 'pacotes de viagens'},
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
